const KEY='SMART_WELL_DB_V1';
const base={settings:{name:'البئر الارتوازي الذكي',owner:'',phone:'',location:'',hourPrice:3000,tripPrice:0,currency:'ريال يمني',debtLimit:50000},customers:[],bookings:[],sales:[],payments:[],expenses:[],fuel:[],maintenance:[],shifts:[],active:null,audit:[]};
let db=load(),page='dashboard',ledgerId='',timer=null;
function load(){try{return Object.assign({},base,JSON.parse(localStorage.getItem(KEY)||'{}'))}catch(e){return JSON.parse(JSON.stringify(base))}}
function save(){localStorage.setItem(KEY,JSON.stringify(db));document.getElementById('status').textContent='● محفوظ محليًا'}
function id(p){return p+'-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7)}
function esc(x){return String(x==null?'':x).replace(/[&<>"']/g,function(m){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]})}
function money(x){return new Intl.NumberFormat('ar-YE',{maximumFractionDigits:0}).format(Number(x)||0)+' '+(db.settings.currency||'ريال')}
function today(){return new Date().toISOString().slice(0,10)}
function now(){return new Date().toTimeString().slice(0,5)}
function fmt(d){return d?new Date(d+'T00:00:00').toLocaleDateString('ar-YE',{year:'numeric',month:'short',day:'numeric'}):'—'}
function cust(id){return db.customers.find(function(x){return x.id===id})}
function balance(id){return db.sales.filter(function(x){return x.customerId===id}).reduce(function(a,x){return a+Number(x.total||0)},0)-db.payments.filter(function(x){return x.customerId===id}).reduce(function(a,x){return a+Number(x.amount||0)},0)}
function toast(s,kind){var t=document.getElementById('toast');t.textContent=s;t.className='show '+(kind||'');setTimeout(function(){t.className=''},2500)}
function audit(a,d){db.audit.unshift({id:id('AUD'),date:today(),time:now(),action:a,details:d});save()}
function go(p){page=p;ledgerId='';document.querySelectorAll('.side nav button').forEach(function(b){b.classList.toggle('active',b.dataset.page===p)});render();document.getElementById('side').classList.remove('open')}
var titles={dashboard:'لوحة التحكم',bookings:'الحجوزات والأدوار',pumping:'الضخ والتعبئة',customers:'العملاء والمزارعون',ledger:'كشف الحساب',payments:'التحصيل والديون',shifts:'الورديات والصندوق',expenses:'المصروفات والديزل',maintenance:'الصيانة',reports:'التقارير',settings:'الإعدادات'};
function render(){document.getElementById('title').textContent=titles[page];document.getElementById('date').textContent=new Date().toLocaleDateString('ar-YE',{weekday:'long',year:'numeric',month:'long',day:'numeric'});var fn={dashboard:dashboard,bookings:bookings,pumping:pumping,customers:customers,ledger:ledger,payments:payments,shifts:shifts,expenses:expenses,maintenance:maintenance,reports:reports,settings:settings}[page];document.getElementById('app').innerHTML=fn();bind();if(db.active)startClock()}
function head(h,p,btn){return '<div class="head"><div><h1>'+h+'</h1><p>'+p+'</p></div><div class="actions">'+(btn||'')+'</div></div>'}
function opts(sel){return '<option value="">اختر العميل</option>'+db.customers.map(function(c){return '<option value="'+c.id+'" '+(c.id===sel?'selected':'')+'>'+esc(c.name)+' '+esc(c.phone||'')+'</option>'}).join('')}
function dashboard(){
var s=db.sales.filter(function(x){return x.date===today()}),cash=s.filter(function(x){return x.type==='cash'}).reduce(function(a,x){return a+Number(x.total)},0)+db.payments.filter(function(x){return x.date===today()}).reduce(function(a,x){return a+Number(x.amount)},0),exp=db.expenses.filter(function(x){return x.date===today()}).reduce(function(a,x){return a+Number(x.amount)},0)+db.fuel.filter(function(x){return x.date===today()}).reduce(function(a,x){return a+Number(x.cost)},0),mins=s.reduce(function(a,x){return a+Number(x.minutes||0)},0);
var up=db.bookings.filter(function(x){return x.date>=today()&&x.status!=='cancelled'}).sort(function(a,b){return (a.date+a.start).localeCompare(b.date+b.start)}).slice(0,5);
var debt=db.customers.map(function(c){return {c:c,b:balance(c.id)}}).filter(function(x){return x.b>0}).sort(function(a,b){return b.b-a.b}).slice(0,5);
return head('مرحبًا بك في البئر الذكي','إدارة التشغيل والحجوزات والحسابات من مكان واحد.','<button class="btn primary" onclick="saleModal()">＋ عملية ضخ</button>')+
'<div class="cards"><div class="card stat"><small>إيرادات اليوم</small><strong>'+money(s.reduce(function(a,x){return a+Number(x.total)},0))+'</strong><span>'+s.length+' عملية</span></div><div class="card stat"><small>النقدية المحصلة</small><strong>'+money(cash)+'</strong><span>مبيعات نقدية + تحصيل</span></div><div class="card stat"><small>ساعات التشغيل</small><strong>'+(mins/60).toFixed(1)+'</strong><span>اليوم</span></div><div class="card stat"><small>مصروفات اليوم</small><strong>'+money(exp)+'</strong><span>الصافي '+money(cash-exp)+'</span></div></div>'+
'<div class="grid2"><div class="panel"><div class="panel-head"><h3>العمليات القادمة</h3><small>'+up.length+' حجوزات</small></div>'+(up.length?'<div class="list">'+up.map(function(b){var c=cust(b.customerId);return '<div class="row"><div><b>'+esc(c?c.name:b.customerName)+'</b><small>'+fmt(b.date)+' · '+b.start+' - '+b.end+'</small></div><span class="badge info">مجدول</span></div>'}).join('')+'</div>':'<div class="empty">لا توجد حجوزات قادمة.</div>')+'</div>'+
'<div class="panel"><div class="panel-head"><h3>أعلى أرصدة العملاء</h3><small>ديون قائمة</small></div>'+(debt.length?'<div class="list">'+debt.map(function(x){return '<div class="row"><span>'+esc(x.c.name)+'</span><b>'+money(x.b)+'</b></div>'}).join('')+'</div>':'<div class="empty">لا توجد ديون قائمة.</div>')+'</div></div>'+
'<div class="panel" style="margin-top:14px"><div class="panel-head"><h3>الوصول السريع</h3></div><div class="quick"><button onclick="go(\'pumping\')"><b>▶ تشغيل الضخ</b><small>مؤقت دقيق</small></button><button onclick="customerModal()"><b>♙ إضافة عميل</b><small>ملف جديد</small></button><button onclick="paymentModal()"><b>﷼ تسجيل تحصيل</b><small>تحديث الرصيد</small></button><button onclick="go(\'reports\')"><b>▦ التقارير</b><small>تحليل الأداء</small></button></div></div>'
}
function bookings(){var rows=db.bookings.slice().sort(function(a,b){return (b.date+b.start).localeCompare(a.date+a.start)});return head('الحجوزات والأدوار','جدولة أدوار السقي ومتابعة المواعيد.','<button class="btn primary" onclick="bookingModal()">＋ حجز جديد</button>')+'<div class="panel"><div class="filters"><input id="bq" placeholder="بحث باسم العميل أو الهاتف"><input id="bd" type="date" value="'+today()+'"><select id="bs"><option value="">كل الحالات</option><option value="scheduled">مجدول</option><option value="completed">مكتمل</option><option value="cancelled">ملغي</option></select></div><div class="table-wrap"><table class="table"><thead><tr><th>التاريخ</th><th>العميل</th><th>الوقت</th><th>الحالة</th><th>إجراء</th></tr></thead><tbody id="brows">'+bookingRows(rows)+'</tbody></table></div></div>'}
function bookingRows(rows){if(!rows.length)return '<tr><td colspan="5"><div class="empty">لا توجد حجوزات.</div></td></tr>';return rows.map(function(b){var c=cust(b.customerId);return '<tr><td>'+fmt(b.date)+'</td><td><b>'+esc(c?c.name:b.customerName)+'</b><br><small>'+esc(c?c.phone:'')+'</small></td><td>'+b.start+' - '+b.end+'</td><td><span class="badge '+(b.status==='completed'?'ok':b.status==='cancelled'?'bad':'info')+'">'+(b.status==='completed'?'مكتمل':b.status==='cancelled'?'ملغي':'مجدول')+'</span></td><td><button class="btn light" onclick="completeBooking(\''+b.id+'\')">✓</button> <button class="btn light" onclick="bookWA(\''+b.id+'\')">واتساب</button> <button class="btn danger" onclick="delBooking(\''+b.id+'\')">حذف</button></td></tr>'}).join('')}
function bookingModal(){if(!db.customers.length){toast('أضف عميلًا أولًا','warn');return}modal('إضافة حجز جديد','<form id="bf" class="form"><div class="field"><label>العميل</label><select name="customerId" required>'+opts('')+'</select></div><div class="field"><label>التاريخ</label><input name="date" type="date" value="'+today()+'" required></div><div class="field"><label>وقت البداية</label><input name="start" type="time" value="07:00" required></div><div class="field"><label>وقت النهاية</label><input name="end" type="time" value="08:00" required></div><div class="field full"><label>ملاحظات</label><textarea name="notes"></textarea></div><div class="modal-actions full"><button class="btn primary">حفظ الحجز</button><button type="button" class="btn light" onclick="closeModal()">إلغاء</button></div></form>');document.getElementById('bf').onsubmit=function(e){e.preventDefault();var f=new FormData(e.target);db.bookings.push({id:id('BKG'),customerId:f.get('customerId'),date:f.get('date'),start:f.get('start'),end:f.get('end'),status:'scheduled',notes:f.get('notes')});audit('إضافة حجز','');closeModal();render();toast('تم حفظ الحجز','success')}}
function completeBooking(i){var b=db.bookings.find(function(x){return x.id===i});if(b){b.status='completed';audit('إكمال حجز',i);render()}}
function delBooking(i){if(confirm('حذف الحجز؟')){db.bookings=db.bookings.filter(function(x){return x.id!==i});audit('حذف حجز',i);render()}}
function bookWA(i){var b=db.bookings.find(function(x){return x.id===i}),c=cust(b.customerId);if(!c||!c.phone){toast('لا يوجد رقم هاتف','warn');return}var m='مرحبًا '+c.name+'، نؤكد لكم موعد السقي بتاريخ '+fmt(b.date)+' من الساعة '+b.start+' إلى '+b.end+'. '+db.settings.name;window.open('https://wa.me/'+c.phone.replace(/\D/g,'')+'?text='+encodeURIComponent(m),'_blank')}
function pumping(){var a=db.active,c=a?cust(a.customerId):null;return head('الضخ والتعبئة','تشغيل المؤقت أو تسجيل عملية يدوية.','<button class="btn primary" onclick="saleModal()">＋ تسجيل عملية</button>')+(a?'<div class="timer"><p>عملية ضخ جارية · '+esc(c?c.name:'عميل')+'</p><div class="clock" id="clock">00:00:00</div><div class="actions"><button class="btn danger" onclick="stopTimer()">⏹ إيقاف الضخ</button><button class="btn light" onclick="cancelTimer()">إلغاء</button></div></div>':'<div class="panel"><div class="alert">اضغط «بدء الضخ» لحساب المدة تلقائيًا.</div><button class="btn primary" onclick="startTimer()">▶ بدء الضخ</button></div>')+'<div class="panel" style="margin-top:14px"><div class="panel-head"><h3>عمليات اليوم</h3><small>'+db.sales.filter(function(x){return x.date===today()}).length+' عمليات</small></div><div class="table-wrap"><table class="table"><thead><tr><th>الوقت</th><th>العميل</th><th>المدة</th><th>النوع</th><th>القيمة</th></tr></thead><tbody>'+db.sales.filter(function(x){return x.date===today()}).slice().reverse().map(function(s){var c=cust(s.customerId);return '<tr><td>'+s.time+'</td><td>'+esc(c?c.name:'—')+'</td><td>'+Math.floor((s.minutes||0)/60)+'س '+((s.minutes||0)%60)+'د</td><td>'+(s.saleMode==='trip'?'نقلة':'وقت')+' · '+(s.type==='cash'?'نقدي':'آجل')+'</td><td><b>'+money(s.total)+'</b></td></tr>'}).join('')||'<tr><td colspan="5"><div class="empty">لا توجد عمليات اليوم.</div></td></tr>'+'</tbody></table></div></div>'}
function startTimer(){if(!db.customers.length){toast('أضف عميلًا أولًا','warn');return}modal('بدء عملية ضخ','<form id="tf" class="form"><div class="field full"><label>العميل</label><select name="customerId" required>'+opts('')+'</select></div><div class="field"><label>نوع البيع</label><select name="saleMode"><option value="time">بالوقت</option><option value="trip">بالنقلة</option></select></div><div class="field"><label>السداد</label><select name="type"><option value="cash">نقدي</option><option value="credit">آجل</option></select></div><div class="modal-actions full"><button class="btn primary">بدء المؤقت</button></div></form>');document.getElementById('tf').onsubmit=function(e){e.preventDefault();var f=new FormData(e.target);db.active={customerId:f.get('customerId'),saleMode:f.get('saleMode'),type:f.get('type'),start:Date.now()};save();closeModal();render();toast('بدأ الضخ','success')}}
function startClock(){clearInterval(timer);timer=setInterval(function(){var el=document.getElementById('clock');if(!el||!db.active){clearInterval(timer);return}var s=Math.floor((Date.now()-db.active.start)/1000),h=Math.floor(s/3600);s%=3600;var m=Math.floor(s/60);s%=60;el.textContent=[h,m,s].map(function(x){return String(x).padStart(2,'0')}).join(':')},500)}
function stopTimer(){var a=db.active;if(!a)return;var mins=Math.max(1,Math.ceil((Date.now()-a.start)/60000));db.active=null;save();saleModal({customerId:a.customerId,minutes:mins,type:a.type,saleMode:a.saleMode})}
function cancelTimer(){if(confirm('إلغاء عملية الضخ؟')){db.active=null;save();render()}}
function saleModal(pre){pre=pre||{};if(!db.customers.length){toast('أضف عميلًا أولًا','warn');return}modal('تسجيل عملية ضخ','<form id="sf" class="form"><div class="field"><label>العميل</label><select name="customerId" required>'+opts(pre.customerId||'')+'</select></div><div class="field"><label>التاريخ</label><input name="date" type="date" value="'+today()+'"></div><div class="field"><label>الوقت</label><input name="time" type="time" value="'+now()+'"></div><div class="field"><label>نوع البيع</label><select name="saleMode"><option value="time" '+(pre.saleMode==='trip'?'':'selected')+'>بالساعة والدقيقة</option><option value="trip" '+(pre.saleMode==='trip'?'selected':'')+'>بالنقلة</option></select></div><div class="field"><label>الدقائق</label><input name="minutes" id="mins" type="number" min="1" value="'+(pre.minutes||60)+'"></div><div class="field"><label>سعر النقلة</label><input name="tripPrice" id="tripPrice" type="number" value="'+db.settings.tripPrice+'"></div><div class="field"><label>السداد</label><select name="type"><option value="cash" '+(pre.type==='credit'?'':'selected')+'>نقدي</option><option value="credit" '+(pre.type==='credit'?'selected':'')+'>آجل</option></select></div><div class="field"><label>القيمة</label><input name="total" id="total" readonly></div><div class="field full"><label>ملاحظات</label><textarea name="notes"></textarea></div><div class="modal-actions full"><button class="btn primary">حفظ العملية</button><button type="button" class="btn light" onclick="closeModal()">إلغاء</button></div></form>');
var f=document.getElementById('sf');function calc(){var mode=f.elements.saleMode.value,mins=Number(f.elements.minutes.value)||0;f.elements.total.value=mode==='trip'?Number(f.elements.tripPrice.value)||0:Math.round(Number(db.settings.hourPrice||0)*mins/60)}f.querySelectorAll('input,select').forEach(function(x){x.oninput=calc});calc();f.onsubmit=function(e){e.preventDefault();var x=new FormData(f),total=Number(x.get('total')),cid=x.get('customerId');if(x.get('type')==='credit'&&balance(cid)+total>Number(cust(cid).debtLimit||db.settings.debtLimit)){toast('تجاوز سقف الدين المحدد للعميل','bad');return}var s={id:id('SAL'),customerId:cid,date:x.get('date'),time:x.get('time'),minutes:x.get('saleMode')==='trip'?0:Number(x.get('minutes')),saleMode:x.get('saleMode'),type:x.get('type'),total:total,notes:x.get('notes')};db.sales.push(s);audit('تسجيل عملية بيع',s.id);closeModal();render();toast('تم تسجيل العملية','success')}}
function customers(){return head('العملاء والمزارعون','ملفات العملاء وأرقام التواصل والأرصدة.','<button class="btn primary" onclick="customerModal()">＋ عميل جديد</button>')+'<div class="panel"><div class="filters"><input id="cq" placeholder="بحث بالاسم أو الهاتف أو المنطقة"></div><div class="table-wrap"><table class="table"><thead><tr><th>العميل</th><th>الهاتف</th><th>المنطقة</th><th>سقف الدين</th><th>الرصيد</th><th>إجراء</th></tr></thead><tbody id="crows">'+customerRows(db.customers)+'</tbody></table></div></div>'}
function customerRows(a){if(!a.length)return '<tr><td colspan="6"><div class="empty">لا يوجد عملاء.</div></td></tr>';return a.map(function(c){return '<tr><td><b>'+esc(c.name)+'</b><br><small>'+esc(c.notes||'')+'</small></td><td>'+esc(c.phone||'—')+'</td><td>'+esc(c.area||'—')+'</td><td>'+money(c.debtLimit||db.settings.debtLimit)+'</td><td><b>'+money(balance(c.id))+'</b></td><td><button class="btn light" onclick="paymentModal(\''+c.id+'\')">تحصيل</button> <button class="btn light" onclick="showLedger(\''+c.id+'\')">كشف</button> <button class="btn danger" onclick="delCustomer(\''+c.id+'\')">حذف</button></td></tr>'}).join('')}
function customerModal(){modal('إضافة عميل','<form id="cf" class="form"><div class="field"><label>اسم العميل</label><input name="name" required></div><div class="field"><label>رقم الهاتف</label><input name="phone"></div><div class="field"><label>المنطقة / الحي</label><input name="area"></div><div class="field"><label>سقف الدين</label><input name="debtLimit" type="number" value="'+db.settings.debtLimit+'"></div><div class="field full"><label>ملاحظات</label><textarea name="notes"></textarea></div><div class="modal-actions full"><button class="btn primary">حفظ</button><button type="button" class="btn light" onclick="closeModal()">إلغاء</button></div></form>');document.getElementById('cf').onsubmit=function(e){e.preventDefault();var f=new FormData(e.target);db.customers.push({id:id('CUS'),name:f.get('name'),phone:f.get('phone'),area:f.get('area'),debtLimit:Number(f.get('debtLimit'))||0,notes:f.get('notes')});audit('إضافة عميل','');closeModal();render();toast('تم حفظ العميل','success')}}
function delCustomer(i){if(db.sales.some(function(x){return x.customerId===i})||db.payments.some(function(x){return x.customerId===i})){toast('لا يمكن حذف عميل لديه حركة مالية','bad');return}if(confirm('حذف العميل؟')){db.customers=db.customers.filter(function(x){return x.id!==i});audit('حذف عميل',i);render()}}
function showLedger(i){ledgerId=i;page='ledger';render()}
function ledger(){var c=cust(ledgerId),sales=db.sales.filter(function(x){return x.customerId===ledgerId}),pay=db.payments.filter(function(x){return x.customerId===ledgerId}),all=sales.map(function(x){return {d:x.date,t:x.time,k:'sale',a:x.total}}).concat(pay.map(function(x){return {d:x.date,t:x.time,k:'pay',a:x.amount}})).sort(function(a,b){return (a.d+a.t).localeCompare(b.d+b.t)});var bal=0;return head('كشف الحساب','كشف تفصيلي للإيرادات والتحصيل والرصيد.','<button class="btn light" onclick="window.print()">🖨 طباعة / PDF</button>')+'<div class="panel"><div class="filters"><select id="lid">'+opts(ledgerId)+'</select></div>'+(c?'<div class="kpis"><div class="kpi"><small>العميل</small><b>'+esc(c.name)+'</b></div><div class="kpi"><small>الاستحقاقات</small><b>'+money(sales.reduce(function(a,x){return a+Number(x.total)},0))+'</b></div><div class="kpi"><small>الرصيد</small><b>'+money(balance(c.id))+'</b></div></div><div class="table-wrap" style="margin-top:12px"><table class="table"><thead><tr><th>التاريخ</th><th>البيان</th><th>استحقاق</th><th>تحصيل</th><th>الرصيد</th></tr></thead><tbody>'+all.map(function(x){bal+=x.k==='sale'?Number(x.a):-Number(x.a);return '<tr><td>'+fmt(x.d)+' '+x.t+'</td><td>'+ (x.k==='sale'?'عملية ضخ':'دفعة سداد')+'</td><td>'+(x.k==='sale'?money(x.a):'—')+'</td><td>'+(x.k==='pay'?money(x.a):'—')+'</td><td><b>'+money(bal)+'</b></td></tr>'}).join('')+'</tbody></table></div>':'<div class="empty">اختر عميلًا لعرض كشف الحساب.</div>')+'</div>'}
function payments(){var ds=db.customers.map(function(c){return {c:c,b:balance(c.id)}}).filter(function(x){return x.b>0}).sort(function(a,b){return b.b-a.b});return head('التحصيل والديون','متابعة الأرصدة وتسجيل الدفعات.','<button class="btn primary" onclick="paymentModal()">＋ تسجيل تحصيل</button>')+'<div class="cards"><div class="card stat"><small>إجمالي الديون</small><strong>'+money(ds.reduce(function(a,x){return a+x.b},0))+'</strong><span>'+ds.length+' عملاء</span></div><div class="card stat"><small>تحصيل اليوم</small><strong>'+money(db.payments.filter(function(x){return x.date===today()}).reduce(function(a,x){return a+Number(x.amount)},0))+'</strong></div></div><div class="panel" style="margin-top:14px"><div class="table-wrap"><table class="table"><thead><tr><th>العميل</th><th>الرصيد</th><th>الهاتف</th><th>إجراء</th></tr></thead><tbody>'+ds.map(function(x){return '<tr><td>'+esc(x.c.name)+'</td><td><b>'+money(x.b)+'</b></td><td>'+esc(x.c.phone||'—')+'</td><td><button class="btn primary" onclick="paymentModal(\''+x.c.id+'\')">سداد</button> <button class="btn light" onclick="debtWA(\''+x.c.id+'\')">مطالبة واتساب</button></td></tr>'}).join('')||'<tr><td colspan="4"><div class="empty">لا توجد ديون قائمة.</div></td></tr>'+'</tbody></table></div></div>'}
function paymentModal(cid){if(!db.customers.length){toast('أضف عميلًا أولًا','warn');return}var b=cid?balance(cid):0;modal('تسجيل تحصيل','<form id="pf" class="form"><div class="field full"><label>العميل</label><select name="customerId" required>'+opts(cid||'')+'</select></div><div class="field"><label>المبلغ</label><input name="amount" type="number" value="'+(b||'')+'" required></div><div class="field"><label>التاريخ</label><input name="date" type="date" value="'+today()+'"></div><div class="field"><label>طريقة الدفع</label><select name="method"><option>نقدي</option><option>تحويل</option><option>أخرى</option></select></div><div class="field full"><label>ملاحظة</label><textarea name="notes"></textarea></div><div class="modal-actions full"><button class="btn primary">حفظ</button></div></form>');document.getElementById('pf').onsubmit=function(e){e.preventDefault();var f=new FormData(e.target),x={id:id('PAY'),customerId:f.get('customerId'),amount:Number(f.get('amount')),date:f.get('date'),time:now(),method:f.get('method'),notes:f.get('notes')};if(x.amount>balance(x.customerId)){toast('المبلغ أكبر من الرصيد','bad');return}db.payments.push(x);audit('تسجيل تحصيل',x.id);closeModal();render();toast('تم تسجيل التحصيل','success')}}
function debtWA(i){var c=cust(i),b=balance(i);if(!c||!c.phone){toast('لا يوجد رقم هاتف','warn');return}var m='نود تذكيركم بأن إجمالي المتبقي عليكم هو '+money(b)+'. '+db.settings.name;window.open('https://wa.me/'+c.phone.replace(/\D/g,'')+'?text='+encodeURIComponent(m),'_blank')}
function shifts(){var open=db.shifts.find(function(x){return x.status==='open'}),rows=db.shifts.slice().reverse().slice(0,10);return head('الورديات والصندوق','مطابقة النقدية الفعلية مع العمليات المسجلة.',open?'<button class="btn danger" onclick="closeShift()">⏹ إغلاق الوردية</button>':'<button class="btn primary" onclick="openShift()">＋ فتح وردية</button>')+(open?'<div class="alert">وردية مفتوحة منذ '+open.startDate+' '+open.startTime+' · '+esc(open.worker)+'</div>':'')+'<div class="panel"><div class="table-wrap"><table class="table"><thead><tr><th>الوردية</th><th>المسؤول</th><th>البداية</th><th>المبيعات</th><th>التحصيل</th><th>الحالة</th></tr></thead><tbody>'+rows.map(function(s){return '<tr><td>'+s.id+'</td><td>'+esc(s.worker)+'</td><td>'+s.startDate+' '+s.startTime+'</td><td>'+money(s.sales||0)+'</td><td>'+money(s.collections||0)+'</td><td><span class="badge '+(s.status==='open'?'info':'ok')+'">'+(s.status==='open'?'مفتوحة':'مغلقة')+'</span></td></tr>'}).join('')||'<tr><td colspan="6"><div class="empty">لا توجد ورديات.</div></td></tr>'+'</tbody></table></div></div>'}
function openShift(){modal('فتح وردية','<form id="shf" class="form"><div class="field"><label>العامل / المشرف</label><input name="worker" required></div><div class="field"><label>الرصيد الافتتاحي</label><input name="opening" type="number" value="0"></div><div class="modal-actions full"><button class="btn primary">فتح الوردية</button></div></form>');document.getElementById('shf').onsubmit=function(e){e.preventDefault();var f=new FormData(e.target);db.shifts.push({id:id('SH'),worker:f.get('worker'),opening:Number(f.get('opening'))||0,startDate:today(),startTime:now(),status:'open'});audit('فتح وردية','');closeModal();render();toast('تم فتح الوردية','success')}}
function closeShift(){var s=db.shifts.find(function(x){return x.status==='open'});if(!s)return;var sales=db.sales.filter(function(x){return x.date>=s.startDate&&x.type==='cash'}).reduce(function(a,x){return a+Number(x.total)},0),col=db.payments.filter(function(x){return x.date>=s.startDate}).reduce(function(a,x){return a+Number(x.amount)},0),expected=s.opening+sales+col;modal('إغلاق الوردية','<div class="alert">النقدية المتوقعة: <b>'+money(expected)+'</b></div><form id="clf"><div class="field"><label>النقدية الفعلية</label><input name="actual" type="number" value="'+expected+'" required></div><div class="modal-actions"><button class="btn primary">إغلاق ومطابقة</button></div></form>');document.getElementById('clf').onsubmit=function(e){e.preventDefault();var actual=Number(new FormData(e.target).get('actual'));Object.assign(s,{sales:sales,collections:col,expected:expected,actual:actual,variance:actual-expected,endDate:today(),endTime:now(),status:'closed'});audit('إغلاق وردية',s.id);closeModal();render();toast('تم الإغلاق. الفرق '+money(s.variance),'success')}}
function expenses(){var all=db.expenses.map(function(x){return {date:x.date,type:'مصروف',desc:x.desc,amount:x.amount}}).concat(db.fuel.map(function(x){return {date:x.date,type:'ديزل',desc:x.desc,amount:x.cost,qty:x.qty}})).sort(function(a,b){return b.date.localeCompare(a.date)});return head('المصروفات والديزل','تسجيل المصروفات التشغيلية والوقود.','<button class="btn primary" onclick="expenseModal(\'expense\')">＋ مصروف</button> <button class="btn secondary" onclick="expenseModal(\'fuel\')">＋ ديزل</button>')+'<div class="panel"><div class="table-wrap"><table class="table"><thead><tr><th>التاريخ</th><th>النوع</th><th>البيان</th><th>الكمية</th><th>القيمة</th></tr></thead><tbody>'+all.map(function(x){return '<tr><td>'+fmt(x.date)+'</td><td><span class="badge '+(x.type==='ديزل'?'warn':'info')+'">'+x.type+'</span></td><td>'+esc(x.desc)+'</td><td>'+(x.qty||'—')+'</td><td><b>'+money(x.amount)+'</b></td></tr>'}).join('')||'<tr><td colspan="5"><div class="empty">لا توجد مصروفات.</div></td></tr>'+'</tbody></table></div></div>'}
function expenseModal(kind){modal(kind==='fuel'?'تسجيل شراء ديزل':'تسجيل مصروف','<form id="ef" class="form"><div class="field"><label>التاريخ</label><input name="date" type="date" value="'+today()+'"></div><div class="field"><label>القيمة</label><input name="amount" type="number" required></div>'+(kind==='fuel'?'<div class="field"><label>الكمية باللتر</label><input name="qty" type="number"></div>':'')+'<div class="field full"><label>البيان</label><input name="desc" required></div><div class="modal-actions full"><button class="btn primary">حفظ</button></div></form>');document.getElementById('ef').onsubmit=function(e){e.preventDefault();var f=new FormData(e.target);if(kind==='fuel')db.fuel.push({id:id('FUEL'),date:f.get('date'),cost:Number(f.get('amount')),qty:Number(f.get('qty'))||0,desc:f.get('desc')});else db.expenses.push({id:id('EXP'),date:f.get('date'),amount:Number(f.get('amount')),desc:f.get('desc')});audit('إضافة '+kind,'');closeModal();render();toast('تم الحفظ','success')}}
function maintenance(){return head('الصيانة','جدولة أعمال الصيانة ومتابعة التنفيذ.','<button class="btn primary" onclick="maintenanceModal()">＋ مهمة صيانة</button>')+'<div class="panel"><div class="table-wrap"><table class="table"><thead><tr><th>المهمة</th><th>الاستحقاق</th><th>ساعات التشغيل</th><th>الحالة</th><th>إجراء</th></tr></thead><tbody>'+db.maintenance.map(function(m){return '<tr><td><b>'+esc(m.title)+'</b><br><small>'+esc(m.notes||'')+'</small></td><td>'+fmt(m.due)+'</td><td>'+esc(m.hours||'—')+'</td><td><span class="badge '+(m.status==='done'?'ok':'warn')+'">'+(m.status==='done'?'منفذة':'معلقة')+'</span></td><td>'+(m.status!=='done'?'<button class="btn success" onclick="doneMaint(\''+m.id+'\')">✓ تنفيذ</button>':'')+'</td></tr>'}).join('')||'<tr><td colspan="5"><div class="empty">لا توجد مهام.</div></td></tr>'+'</tbody></table></div></div>'}
function maintenanceModal(){modal('جدولة صيانة','<form id="mf" class="form"><div class="field full"><label>اسم المهمة</label><input name="title" required placeholder="تغيير زيت المولد"></div><div class="field"><label>تاريخ الاستحقاق</label><input name="due" type="date" value="'+today()+'"></div><div class="field"><label>بعد ساعات تشغيل</label><input name="hours" type="number"></div><div class="field full"><label>ملاحظات</label><textarea name="notes"></textarea></div><div class="modal-actions full"><button class="btn primary">حفظ</button></div></form>');document.getElementById('mf').onsubmit=function(e){e.preventDefault();var f=new FormData(e.target);db.maintenance.push({id:id('MNT'),title:f.get('title'),due:f.get('due'),hours:f.get('hours'),notes:f.get('notes'),status:'pending'});audit('إضافة صيانة','');closeModal();render();toast('تمت الإضافة','success')}}
function doneMaint(i){var m=db.maintenance.find(function(x){return x.id===i});if(m){m.status='done';m.done=today();save();render()}}
function reports(){var mo=today().slice(0,7),s=db.sales.filter(function(x){return x.date.indexOf(mo)===0}),p=db.payments.filter(function(x){return x.date.indexOf(mo)===0}),e=db.expenses.filter(function(x){return x.date.indexOf(mo)===0}),f=db.fuel.filter(function(x){return x.date.indexOf(mo)===0}),rev=s.reduce(function(a,x){return a+Number(x.total)},0),cost=e.reduce(function(a,x){return a+Number(x.amount)},0)+f.reduce(function(a,x){return a+Number(x.cost)},0);var days=[];for(var i=6;i>=0;i--){var d=new Date();d.setDate(d.getDate()-i);var k=d.toISOString().slice(0,10),v=db.sales.filter(function(x){return x.date===k}).reduce(function(a,x){return a+Number(x.total)},0);days.push({k:k,v:v})}var mx=Math.max.apply(null,days.map(function(x){return x.v}).concat([1]));return head('التقارير والتحليلات','ملخص مالي وتشغيلي للشهر الحالي.','<button class="btn light" onclick="window.print()">🖨 طباعة / PDF</button>')+'<div class="cards"><div class="card stat"><small>الإيرادات</small><strong>'+money(rev)+'</strong></div><div class="card stat"><small>التحصيل</small><strong>'+money(s.filter(function(x){return x.type==='cash'}).reduce(function(a,x){return a+Number(x.total)},0)+p.reduce(function(a,x){return a+Number(x.amount)},0))+'</strong></div><div class="card stat"><small>التكاليف</small><strong>'+money(cost)+'</strong></div><div class="card stat"><small>صافي التشغيل</small><strong>'+money(rev-cost)+'</strong></div></div><div class="grid2"><div class="panel"><div class="panel-head"><h3>الإيرادات آخر 7 أيام</h3></div><div class="chart">'+days.map(function(x){return '<div class="bar"><i style="height:'+Math.max(3,(x.v/mx)*145)+'px"></i><small>'+x.k.slice(5)+'</small></div>'}).join('')+'</div></div><div class="panel"><div class="panel-head"><h3>أعلى الديون</h3></div><div class="list">'+db.customers.map(function(c){return {c:c,b:balance(c.id)}}).filter(function(x){return x.b>0}).sort(function(a,b){return b.b-a.b}).slice(0,6).map(function(x){return '<div class="row"><span>'+esc(x.c.name)+'</span><b>'+money(x.b)+'</b></div>'}).join('')||'<div class="empty">لا توجد ديون.</div>'+'</div></div></div>'}
function settings(){return head('الإعدادات','بيانات البئر والأسعار والحدود الائتمانية.','<button class="btn primary" onclick="saveSettings()">حفظ الإعدادات</button>')+'<div class="panel"><div class="form"><div class="field"><label>اسم البئر</label><input id="sn" value="'+esc(db.settings.name)+'"></div><div class="field"><label>اسم المالك</label><input id="so" value="'+esc(db.settings.owner)+'"></div><div class="field"><label>رقم التواصل</label><input id="sp" value="'+esc(db.settings.phone)+'"></div><div class="field"><label>الموقع</label><input id="sl" value="'+esc(db.settings.location)+'"></div><div class="field"><label>سعر الساعة</label><input id="sh" type="number" value="'+db.settings.hourPrice+'"></div><div class="field"><label>سعر النقلة</label><input id="st" type="number" value="'+db.settings.tripPrice+'"></div><div class="field"><label>العملة</label><input id="sc" value="'+esc(db.settings.currency)+'"></div><div class="field"><label>السقف الافتراضي للدين</label><input id="sd" type="number" value="'+db.settings.debtLimit+'"></div></div></div><div class="panel" style="margin-top:14px"><div class="panel-head"><h3>النسخ الاحتياطي</h3></div><div class="actions"><button class="btn light" onclick="backup()">⇩ تنزيل نسخة</button><label class="btn light">⇧ استعادة<input id="restore2" type="file" accept=".json" style="display:none"></label><button class="btn danger" onclick="resetAll()">حذف جميع البيانات</button></div></div>'}
function saveSettings(){Object.assign(db.settings,{name:document.getElementById('sn').value,owner:document.getElementById('so').value,phone:document.getElementById('sp').value,location:document.getElementById('sl').value,hourPrice:Number(document.getElementById('sh').value)||0,tripPrice:Number(document.getElementById('st').value)||0,currency:document.getElementById('sc').value,debtLimit:Number(document.getElementById('sd').value)||0});audit('تعديل الإعدادات','');render();toast('تم حفظ الإعدادات','success')}
function modal(title,html){document.getElementById('modal').innerHTML='<h2>'+title+'</h2>'+html;document.getElementById('modal-bg').classList.add('show')}
function closeModal(){document.getElementById('modal-bg').classList.remove('show');document.getElementById('modal').innerHTML=''}
function backup(){var a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(db,null,2)],{type:'application/json'}));a.download='smart-well-backup-'+today()+'.json';a.click()}
function restore(file){if(!file)return;var r=new FileReader();r.onload=function(){try{var x=JSON.parse(r.result);if(!x.settings||!x.customers)throw 0;db=x;save();render();toast('تمت الاستعادة','success')}catch(e){toast('النسخة غير صالحة','bad')}};r.readAsText(file)}
function resetAll(){if(confirm('سيتم حذف جميع البيانات المحلية. هل أنت متأكد؟')){localStorage.removeItem(KEY);db=load();render()}}
function bind(){document.querySelectorAll('.side nav button').forEach(function(b){b.onclick=function(){go(b.dataset.page)}});document.getElementById('menu').onclick=function(){document.getElementById('side').classList.toggle('open')};var q=document.getElementById('cq');if(q)q.oninput=function(){var v=q.value.toLowerCase();document.getElementById('crows').innerHTML=customerRows(db.customers.filter(function(c){return (c.name+c.phone+c.area).toLowerCase().indexOf(v)>-1}))};var l=document.getElementById('lid');if(l)l.onchange=function(){ledgerId=l.value;render()};var bq=document.getElementById('bq'),bd=document.getElementById('bd'),bs=document.getElementById('bs');if(bq)[bq,bd,bs].forEach(function(x){x.oninput=function(){var q=(bq.value||'').toLowerCase(),d=bd.value,s=bs.value;document.getElementById('brows').innerHTML=bookingRows(db.bookings.filter(function(b){var c=cust(b.customerId);return (!q||(c&&((c.name+c.phone).toLowerCase().indexOf(q)>-1)))&&(!d||b.date===d)&&(!s||b.status===s)}))}});var r=document.getElementById('restore2');if(r)r.onchange=function(){restore(r.files[0])}}
document.getElementById('backup').onclick=backup;document.getElementById('restore').onchange=function(e){restore(e.target.files[0])};document.getElementById('modal-bg').onclick=function(e){if(e.target.id==='modal-bg')closeModal()};render();
